import { MetricType } from '@prisma/client';

export interface DefaultKPI {
  kpiName: string;
  description: string;
  metricType: MetricType;
  unit: string;
  calculationFormula: string;
  measurementMethod: string;
  targetValue?: number;
  dataSource?: string;
  collectionFrequency?: string;
}

export const DEFAULT_KPIS: DefaultKPI[] = [
  // Operational Efficiency
  {
    kpiName: 'Average Response Time',
    description: 'Average time to respond to customer inquiries or process requests',
    metricType: 'OPERATIONAL_EFFICIENCY',
    unit: 'seconds',
    calculationFormula: 'Sum of all response times / Number of requests',
    measurementMethod: 'Track response time for each request from initiation to completion. Calculate average over measurement period.',
    targetValue: 10,
    dataSource: 'Customer service system, API logs',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'Process Automation Rate',
    description: 'Percentage of processes automated vs manual',
    metricType: 'OPERATIONAL_EFFICIENCY',
    unit: 'percentage',
    calculationFormula: '(Automated processes / Total processes) × 100',
    measurementMethod: 'Count total processes and identify which are automated. Calculate percentage.',
    targetValue: 80,
    dataSource: 'Process inventory, automation logs',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Task Completion Time',
    description: 'Average time to complete a standard task',
    metricType: 'OPERATIONAL_EFFICIENCY',
    unit: 'minutes',
    calculationFormula: 'Sum of task completion times / Number of tasks',
    measurementMethod: 'Track start and end times for each task. Calculate average.',
    targetValue: 30,
    dataSource: 'Task management system',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'System Uptime',
    description: 'Percentage of time system is available and operational',
    metricType: 'OPERATIONAL_EFFICIENCY',
    unit: 'percentage',
    calculationFormula: '(Total uptime / Total time) × 100',
    measurementMethod: 'Monitor system availability continuously. Calculate uptime percentage.',
    targetValue: 99.9,
    dataSource: 'Monitoring systems, uptime trackers',
    collectionFrequency: 'daily',
  },

  // Financial Performance
  {
    kpiName: 'Monthly Cost Savings',
    description: 'Cost savings from reduced operational expenses',
    metricType: 'FINANCIAL_PERFORMANCE',
    unit: 'USD',
    calculationFormula: 'Baseline monthly cost - Current monthly cost',
    measurementMethod: 'Compare current operational costs to baseline (pre-AI) costs. Track all cost reductions.',
    targetValue: 25000,
    dataSource: 'Financial systems, cost reports',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Revenue Increase',
    description: 'Additional revenue generated through AI initiatives',
    metricType: 'FINANCIAL_PERFORMANCE',
    unit: 'USD',
    calculationFormula: 'Current revenue - Baseline revenue',
    measurementMethod: 'Track revenue before and after AI implementation. Attribute revenue increases to AI initiatives.',
    targetValue: 100000,
    dataSource: 'Sales systems, revenue reports',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Cost per Transaction',
    description: 'Average cost to process a single transaction',
    metricType: 'FINANCIAL_PERFORMANCE',
    unit: 'USD',
    calculationFormula: 'Total operational costs / Number of transactions',
    measurementMethod: 'Divide total operational costs by number of transactions processed in the period.',
    targetValue: 2.5,
    dataSource: 'Financial systems, transaction logs',
    collectionFrequency: 'weekly',
  },
  {
    kpiName: 'ROI Percentage',
    description: 'Return on investment percentage',
    metricType: 'FINANCIAL_PERFORMANCE',
    unit: 'percentage',
    calculationFormula: '((Benefits - Costs) / Costs) × 100',
    measurementMethod: 'Calculate total benefits (cost savings + revenue increase) minus total costs, divided by costs.',
    targetValue: 200,
    dataSource: 'ROI calculations, financial reports',
    collectionFrequency: 'quarterly',
  },

  // Customer Satisfaction
  {
    kpiName: 'Customer Satisfaction Score',
    description: 'Customer satisfaction rating on a scale',
    metricType: 'CUSTOMER_SATISFACTION',
    unit: 'out of 5',
    calculationFormula: 'Sum of all ratings / Number of responses',
    measurementMethod: 'Collect customer satisfaction ratings (e.g., 1-5 scale) through surveys or feedback forms. Calculate average.',
    targetValue: 4.5,
    dataSource: 'Customer surveys, feedback systems',
    collectionFrequency: 'weekly',
  },
  {
    kpiName: 'Net Promoter Score (NPS)',
    description: 'Measure of customer loyalty and satisfaction',
    metricType: 'CUSTOMER_SATISFACTION',
    unit: 'score',
    calculationFormula: '% Promoters - % Detractors',
    measurementMethod: 'Survey customers: "How likely are you to recommend us?" (0-10 scale). Promoters (9-10), Passives (7-8), Detractors (0-6).',
    targetValue: 50,
    dataSource: 'Customer surveys',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'First Contact Resolution Rate',
    description: 'Percentage of issues resolved on first contact',
    metricType: 'CUSTOMER_SATISFACTION',
    unit: 'percentage',
    calculationFormula: '(Issues resolved on first contact / Total issues) × 100',
    measurementMethod: 'Track whether each customer issue is resolved in the first interaction. Calculate percentage.',
    targetValue: 85,
    dataSource: 'Customer service system',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'Customer Complaint Rate',
    description: 'Number of complaints per 1000 interactions',
    metricType: 'CUSTOMER_SATISFACTION',
    unit: 'per 1000',
    calculationFormula: '(Number of complaints / Total interactions) × 1000',
    measurementMethod: 'Count total complaints and total customer interactions. Calculate rate per 1000.',
    targetValue: 5,
    dataSource: 'Complaint tracking system',
    collectionFrequency: 'weekly',
  },

  // Employee Productivity
  {
    kpiName: 'Tasks Completed per Employee',
    description: 'Average number of tasks completed per employee',
    metricType: 'EMPLOYEE_PRODUCTIVITY',
    unit: 'tasks',
    calculationFormula: 'Total tasks completed / Number of employees',
    measurementMethod: 'Count total tasks completed and divide by number of active employees in the period.',
    targetValue: 50,
    dataSource: 'Task management system, HR systems',
    collectionFrequency: 'weekly',
  },
  {
    kpiName: 'Time Saved per Employee',
    description: 'Average time saved per employee through automation',
    metricType: 'EMPLOYEE_PRODUCTIVITY',
    unit: 'hours',
    calculationFormula: 'Sum of time saved / Number of employees',
    measurementMethod: 'Track time saved through automation tools. Calculate average per employee.',
    targetValue: 10,
    dataSource: 'Time tracking systems, automation logs',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Employee Utilization Rate',
    description: 'Percentage of employee time spent on productive work',
    metricType: 'EMPLOYEE_PRODUCTIVITY',
    unit: 'percentage',
    calculationFormula: '(Productive hours / Total hours) × 100',
    measurementMethod: 'Track productive vs non-productive hours. Calculate percentage.',
    targetValue: 85,
    dataSource: 'Time tracking systems',
    collectionFrequency: 'weekly',
  },

  // Quality Improvement
  {
    kpiName: 'Error Rate',
    description: 'Percentage of errors or defects in output',
    metricType: 'QUALITY_IMPROVEMENT',
    unit: 'percentage',
    calculationFormula: '(Number of errors / Total outputs) × 100',
    measurementMethod: 'Track all errors or defects identified. Calculate percentage of total outputs.',
    targetValue: 1,
    dataSource: 'Quality assurance systems, error logs',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'Accuracy Rate',
    description: 'Percentage of accurate outputs or predictions',
    metricType: 'QUALITY_IMPROVEMENT',
    unit: 'percentage',
    calculationFormula: '(Correct outputs / Total outputs) × 100',
    measurementMethod: 'Validate outputs against ground truth or expected results. Calculate accuracy percentage.',
    targetValue: 95,
    dataSource: 'Validation systems, quality checks',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'Defect Rate',
    description: 'Number of defects per 1000 units',
    metricType: 'QUALITY_IMPROVEMENT',
    unit: 'per 1000',
    calculationFormula: '(Number of defects / Total units) × 1000',
    measurementMethod: 'Count defects found in quality checks. Calculate rate per 1000 units produced.',
    targetValue: 10,
    dataSource: 'Quality control systems',
    collectionFrequency: 'weekly',
  },

  // Risk & Compliance
  {
    kpiName: 'Compliance Score',
    description: 'Percentage of compliance requirements met',
    metricType: 'RISK_COMPLIANCE',
    unit: 'percentage',
    calculationFormula: '(Requirements met / Total requirements) × 100',
    measurementMethod: 'Audit compliance against all applicable requirements. Calculate percentage met.',
    targetValue: 100,
    dataSource: 'Compliance audits, regulatory systems',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Security Incident Rate',
    description: 'Number of security incidents per month',
    metricType: 'RISK_COMPLIANCE',
    unit: 'incidents',
    calculationFormula: 'Count of security incidents in period',
    measurementMethod: 'Track all security incidents (breaches, vulnerabilities, etc.). Count per period.',
    targetValue: 0,
    dataSource: 'Security monitoring systems',
    collectionFrequency: 'monthly',
  },

  // Adoption & Engagement
  {
    kpiName: 'User Adoption Rate',
    description: 'Percentage of users actively using the AI system',
    metricType: 'ADOPTION_ENGAGEMENT',
    unit: 'percentage',
    calculationFormula: '(Active users / Total users) × 100',
    measurementMethod: 'Count users who have used the system in the period. Calculate percentage of total users.',
    targetValue: 80,
    dataSource: 'User activity logs, analytics',
    collectionFrequency: 'weekly',
  },
  {
    kpiName: 'Daily Active Users',
    description: 'Number of unique users using the system daily',
    metricType: 'ADOPTION_ENGAGEMENT',
    unit: 'users',
    calculationFormula: 'Count of unique users per day',
    measurementMethod: 'Track unique user logins or interactions per day. Count distinct users.',
    targetValue: 500,
    dataSource: 'User activity logs',
    collectionFrequency: 'daily',
  },
  {
    kpiName: 'Feature Usage Rate',
    description: 'Percentage of available features being used',
    metricType: 'ADOPTION_ENGAGEMENT',
    unit: 'percentage',
    calculationFormula: '(Features used / Total features) × 100',
    measurementMethod: 'Track which features are accessed. Calculate percentage of total features used.',
    targetValue: 70,
    dataSource: 'Feature usage analytics',
    collectionFrequency: 'monthly',
  },

  // Innovation Velocity
  {
    kpiName: 'Time to Market',
    description: 'Average time from idea to deployment',
    metricType: 'INNOVATION_VELOCITY',
    unit: 'days',
    calculationFormula: 'Sum of development cycles / Number of projects',
    measurementMethod: 'Track time from project initiation to production deployment. Calculate average.',
    targetValue: 30,
    dataSource: 'Project management systems',
    collectionFrequency: 'monthly',
  },
  {
    kpiName: 'Innovation Rate',
    description: 'Number of new features or improvements per quarter',
    metricType: 'INNOVATION_VELOCITY',
    unit: 'features',
    calculationFormula: 'Count of new features deployed in period',
    measurementMethod: 'Count all new features, improvements, or innovations deployed in the period.',
    targetValue: 10,
    dataSource: 'Release notes, deployment logs',
    collectionFrequency: 'quarterly',
  },
];

